#!/usr/bin/env zsh

alias ..='cd ..'
alias bake='bundle exec rake'
alias be='bundle exec'
alias bec='bundle exec rails c'
alias ber='bundle exec rspec'
alias bes='bundle exec rails s'
alias cat='bat'
alias de='docker exec -it'
alias dl='docker logs -f --tail 100'
alias dop='docker stop'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}"'
alias dr='docker restart'
alias ds='docker start'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdl='git diff `git rev-parse @~`'
alias gdm='git diff master'
alias gh='git hs'
alias gl='git log'
alias gn='git newb'
alias gs='git status -s'
alias gull='git pull'
alias ht='heytmux TMUX_WORKSPACE.yml'
alias j='fasd_cd -d'
alias jj='fasd_cd -d -i'
alias l.='fd -Hd 1 "^\." | xargs exa -lad'
alias l='exa -l'
alias la='exa -la'
alias less='bat'
alias ll='fd -Hd 1 -t l | xargs exa -la'
alias ls='exa'
alias lt='exa -laT'
alias mc='iex -S mix'
alias ml='mix lint'
alias ms='mix phx.server'
alias mt='mix test --trace'
alias mtd='iex -S mix test --trace'
alias s.='source ~/.zshrc'
alias ta='tmate'
alias taa='tmate -S `tmate-socket` attach'
alias tal='tmate -S `tmate-socket` ls'
alias tma='tmux attach'
alias tmate-ssh='tmate -S `tmate-socket` display -p "#{tmate_ssh}"  | tr -d "\n" | pbcopy'
alias tml='tmux ls'
alias up='brew upgrade -s; brew cleanup; antibody update; vim -c "PlugUpdate|qa";'
alias v='my_vim'
alias vi='my_vim'
alias vim='my_vim'

if [[ "$TMUX" =~ "/tmate-" ]]; then
  alias tmux="TMUX='' tmux"
fi
