#!/usr/bin/env zsh

alias ..='cd ..'
alias bake='bundle exec rake'
alias be='bundle exec'
alias bec='bundle exec rails c'
alias bes='bundle exec rails s'
alias ber='bundle exec rspec'
alias cat='bat'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Command}}\t{{.Image}}"'
alias de='docker exec -it'
alias dl='docker logs -f'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdl='git diff `git rev-parse @~`'
alias gdm='git diff master'
alias gh='git hs'
alias gl='git log'
alias gn='git newb'
alias gs='git status -s'
alias gull='git pull'
alias gush='git push'
alias ht='heytmux TMUX_WORKSPACE.yml'
alias j='fasd_cd -d'
alias jj='fasd_cd -d -i'
alias l.='fd -Hd 1 "^\." | xargs exa -lad'
alias l='exa -l'
alias la='exa -la'
alias less='bat'
alias ll='fd -Hd 1 -t l | xargs exa -la'
alias ls='exa'
alias lt='exa -laT'
alias mc='iex -S mix'
alias ml='mix lint'
alias ms='mix phx.server'
alias mt='mix test --trace'
alias mtd='iex -S mix test --trace'
alias s.='source ~/.zshrc'
alias ta='tmate'
alias taa='tmate -S `tmate-socket` attach'
alias tal='tmate -S `tmate-socket` ls'
alias tma='tmux attach'
alias tml='tmux ls'
alias tmate-ssh='tmate -S `tmate-socket` display -p "#{tmate_ssh}"  | tr -d "\n" | pbcopy'
alias up='brew upgrade -s; brew cleanup; antibody update; vim -c "PlugUpdate|qa";'
alias vim='vim -c "call util#last_buffer(0)"'
alias vi='vim'
alias v='vim'

if [[ "$TMUX" =~ "/tmate-" ]]; then
  alias tmux="TMUX='' tmux"
fi
