#!/usr/bin/env zsh

alias ..='cd ..'
alias bake='bundle exec rake'
alias be='bundle exec'
alias bec='bundle exec rails c'
alias ber='bundle exec rspec'
alias bes='bundle exec rails s'
alias cat='bat'
alias gco='git checkout'
alias gd='git diff'
alias gdm='git diff main'
alias gh='git hs'
alias gl='git log'
alias gs='git status -s'
alias gull='git pull'
alias j='z'
alias ji='zi'
alias less='bat'
alias ls='ls -l --color=auto'
alias s.='source ~/.zshrc'
alias up='brew upgrade; brew cleanup -s; antidote update; vim -c "PlugUpdate|qa";'
alias vim='my_vim'
